[install]
# Use the exact versions specified in package.json
exact = true

# Install peer dependencies automatically
peer = true

# Install dev dependencies by default
dev = true

[test]
# Use the same environment variables as your app
env = true

[run]
# Set the default command to run
default = "dev"
