[build]
  command = "npm install --include=optional && npm run build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_FLAGS = "--include=optional"
  NETLIFY_USE_YARN = "false"
  CI = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
