[build]
  command = "npm ci --production=false && NODE_OPTIONS='--max_old_space_size=3072' VITE_BUILD_MINIFY=true VITE_BUILD_SOURCEMAP=false npm run build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_FLAGS = "--no-optional"
  NETLIFY_USE_YARN = "false"
  CI = "true"
  NETLIFY_IGNORE_PYTHON = "true"
  NETLIFY_IGNORE_RUBY = "true"
  NODE_OPTIONS = "--max_old_space_size=3072"
  VITE_BUILD_MINIFY = "true"
  VITE_BUILD_SOURCEMAP = "false"

[build.cache]
  node_modules = "true"
  node_version = "true"
  build = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://*; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://*;"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
