name: Deploy to Vercel with Context7 Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  document:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Generate Context7 Documentation
        uses: context7/context7-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
  deploy:
    runs-on: ubuntu-latest
    needs: document
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        env:
          NODE_OPTIONS: '--max_old_space_size=3072'
          VITE_BUILD_MINIFY: 'true'
          VITE_BUILD_SOURCEMAP: 'false'
      
      # Note: The following steps may show context access warnings in IDE,
      # but they will work correctly in the actual GitHub Actions environment.
      # These warnings are due to GitHub's static analysis being cautious about
      # how secrets are used in YAML files.
      
      # Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install -g vercel@latest
      
      # Deploy to Vercel using the official approach
      - name: Deploy to Vercel (Production)
        if: github.event_name == 'push'
        run: vercel --token ${VERCEL_TOKEN} --prod --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      
      - name: Deploy to Vercel (Preview)
        if: github.event_name == 'pull_request'
        run: vercel --token ${VERCEL_TOKEN} --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
