name: Deploy to Vercel with Bun

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Run tests
        run: bun test
        
      - name: Build Storybook
        run: bun run build-storybook
        
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: chpt_29d9d3f461ad26f
          storybookBuildDir: storybook-static
          exitZeroOnChanges: true # Optional: prevents the workflow from failing on UI changes
          
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: coverage/
          retention-days: 30

  deploy:
    needs: test
    runs-on: ubuntu-latest
    # Note: Context access warnings in IDE static analysis won't affect actual deployment functionality
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Generate Context7 Documentation
        run: bun run build:docs
        
      - name: Deploy to Vercel (Production)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: bunx vercel --prod --token=$VERCEL_TOKEN --yes
        
      - name: Deploy to Vercel (Preview)
        if: github.event_name == 'pull_request'
        run: bunx vercel --token=$VERCEL_TOKEN --yes
